num = int(input("Please give me a number. \n"))
num1 = int(input("Please give me a second number. \n"))
num3 = str(num + num1)
num4 = str(num - num1)
num5 = str(num * num1)
num6 = str(num / num1)
print("The sum between your first and second number is " + str(num3))
print("The difference between your first and second number is " + str(num4))
print("The product between your first and second number is " + str(num5))
print("The quotient between your first and second number is " + str(num6))
print("To recap, your sum is " + str(num3) + ", your difference is " + str(num4) + ", your product is " + str(num5) + ", and finally your quotient is " + str(num6) + ".")